package net.devcouch.assertj;

import net.devcouch.assertj.animals.Cat;
import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link Cat} specific assertions - Generated by CustomAssertionGenerator.
 */
public class CatAssert extends AbstractAssert<CatAssert, Cat> {

  /**
   * Creates a new <code>{@link CatAssert}</code> to make assertions on actual Cat.
   * @param actual the Cat we want to make assertions on.
   */
  public CatAssert(Cat actual) {
    super(actual, CatAssert.class);
  }

  /**
   * An entry point for CatAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myCat)</code> and get specific assertion with code completion.
   * @param actual the Cat we want to make assertions on.
   * @return a new <code>{@link CatAssert}</code>
   */
  public static CatAssert assertThat(Cat actual) {
    return new CatAssert(actual);
  }

  /**
   * Verifies that the actual Cat's name is equal to the given one.
   * @param name the given name to compare the actual Cat's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Cat's name is not equal to the given one.
   */
  public CatAssert hasName(String name) {
    // check that actual Cat we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.name;
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

}
