package net.devcouch.assertj;

import net.devcouch.assertj.animals.Dog;
import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link Dog} specific assertions - Generated by CustomAssertionGenerator.
 */
public class DogAssert extends AbstractAssert<DogAssert, Dog> {

  /**
   * Creates a new <code>{@link DogAssert}</code> to make assertions on actual Dog.
   * @param actual the Dog we want to make assertions on.
   */
  public DogAssert(Dog actual) {
    super(actual, DogAssert.class);
  }

  /**
   * An entry point for DogAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myDog)</code> and get specific assertion with code completion.
   * @param actual the Dog we want to make assertions on.
   * @return a new <code>{@link DogAssert}</code>
   */
  public static DogAssert assertThat(Dog actual) {
    return new DogAssert(actual);
  }

  /**
   * Verifies that the actual Dog's name is equal to the given one.
   * @param name the given name to compare the actual Dog's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Dog's name is not equal to the given one.
   */
  public DogAssert hasName(String name) {
    // check that actual Dog we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.name;
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

}
