package net.devcouch.assertj;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link Main} specific assertions - Generated by CustomAssertionGenerator.
 */
public class MainAssert extends AbstractAssert<MainAssert, Main> {

  /**
   * Creates a new <code>{@link MainAssert}</code> to make assertions on actual Main.
   * @param actual the Main we want to make assertions on.
   */
  public MainAssert(Main actual) {
    super(actual, MainAssert.class);
  }

  /**
   * An entry point for MainAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myMain)</code> and get specific assertion with code completion.
   * @param actual the Main we want to make assertions on.
   * @return a new <code>{@link MainAssert}</code>
   */
  public static MainAssert assertThat(Main actual) {
    return new MainAssert(actual);
  }

}
